# Generated by Django 5.2.5 on 2025-08-11 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_alter_user_managers"),
    ]

    operations = [
        # Remove the old name field
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        # Add new fields
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='additional_info',
            field=models.TextField(blank=True, help_text='Any additional information about the user'),
        ),
        # Modify existing fields to match AbstractUser defaults
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
